# Generated by Django 4.2.6 on 2023-10-20 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TodoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=50)),
                (
                    "due",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 10, 20, 14, 33, 42, 318182)
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("high", "HIGH"),
                            ("medium", "MEDIUM"),
                            ("low", "LOW"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "completion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending", "PENDING"),
                            ("progressing", "PROGRESSING"),
                            ("completed", "COMPLETED"),
                            ("overdue", "OVERDUE"),
                        ],
                        default="PENDING",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
