# Generated by Django 4.2.6 on 2023-10-20 22:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Todo", "0002_remove_todoitem_due_todoitem_end_todoitem_start"),
    ]

    operations = [
        migrations.AddField(
            model_name="todoitem",
            name="is_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="todoitem",
            name="start",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 21, 1, 23, 42, 693374)
            ),
        ),
    ]
